language: node_js
node_js:
  - "7"
before_install:
  - git checkout ssg
  - git clone . -b master pages
install:
  - npm install
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
