language: node_js
node_js:
  - "7"
before_install:
  - git clone -b master https://github.com/sillyslux/fluxbox-wiki.git pages
  - ls
script: npm run-script travis-build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: ssg
