language: node_js
node_js:
  - "7"
script:
  - env
  - git log -n 3
  - git branch
  - cat .git/config
  - node -e "e=process.env;d='';require('https').get({hostname:'api.github.com',path:'/repos/'+e.TRAVIS_REPO_SLUG+'/git/commits/'+e.TRAVIS_COMMIT, headers:{'User-Agent':'travis'}},res=>{res.on('data',c=>d+=c);res.on('end',()=>{console.log(d);d=JSON.parse(d);o={request:{config:{env:{C_AUTHOR_NAME:d.author.name,C_AUTHOR_MAIL:d.author.email,C_COMMITTER_NAME:d.committer.name,C_COMMITTER_MAIL:d.committer.email,C_MESSAGE:d.message,C_URL:d.html_url}}}};if(e.TRAVIS_EVENT_TYPE==="pull_request")o.request.config.env.C_PR=e.TRAVIS_PULL_REQUEST;p=JSON.stringify(o);require('https').request({hostname:'api.travis-ci.org',path:'/repo/sillyslux%2Ffluxbox-wiki-ssg/requests',method:'POST',headers:{'Content-Type':'application/json','Accept':'application/vnd.travis-ci.2+json','Travis-API-Version':'3','Authorization':'token '+e.TRAVIS_TOKEN,'Content-Length':Buffer.byteLength(p)}},res=>res.on('data',f=>console.log(f.toString()))).write(p)})})"

git:
  depth: 1
branches:
  only:
  - master
