language: node_js
node_js:
  - "7"
before_install:
  - git clone -b master https://github.com/sillyslux/fluxbox-wiki.git pages
  - cp -r _pages/* pages
script: npm run-script travis-build
before_deploy:
  - rm -rf css config.toml utils package.json editor fonts html.js loaders node_modules gatsby-browser.js i18n.toml .eslintrc wrappers gatsby-node.js LICENSE .travis.yml static custom README.md .gitignore pages
  - mv public/* .
  - ls -la public
  - ls -la .
  - rm public/.styles.css && rmdir public
  - env
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: ssg
git:
  depth: 1
branches:
  only:
  - master
  - ssg
