language: node_js
node_js:
  - "7"
before_install:
  - git clone -b master https://github.com/sillyslux/fluxbox-wiki.git pages
  - ls
script: npm run-script travis-build
before_deploy:
  - rm -r css config.toml utils package.json editor fonts html.js loaders gatsby-browser.js i18n.toml .eslintrc wrappers gatsby-node.js LICENSE .travis.yml static custom README.md .gitignore
  - mv pages/* .
  - ls -la pages
  - rm pages/.styles.css && rmdir pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: ssg
